##
## DEPLOYMENT
##

# Updated new manuel to developers.gambio.de page

stages:
    - deploy


before_script:
    - which python
    - which pip
    - /usr/bin/python3 -m pip install --upgrade pip
    - /usr/bin/python3 -m pip install mkdocs-material
build:
    stage: deploy
    environment:
        name: Testing
        url: https://tt.supp.gambio-server.net/manual/
    script:
        - '# generate manual with mkdocs'
        - ./src/build.sh v4.2.0.0
        - rm -r .git # Remove git directory before upload
        - scp -r ./dist/* redmine:/var/www/developers.gambio.de/docs/manual/
    only:
        - master