##
## DEPLOYMENT
##

# Updated new manuel to developers.gambio.de page

before_script:
    - pip install --upgrade pip && pip install mkdocs
generate:
    stage: build
    script:
        - '# generate manual with mkdocs'
        - ./src/build.sh v4.2.0.0
    only:
        - master


upload:
    stage: deploy
    script:
        - '# Removed files that should not be deployed'
        - rsync -a --delete dist/ testshops:/var/www/tt/manual/
    only:
        - master
