##
## DEPLOYMENT
##

# Updated new manuel to developers.gambio.de page

stages:
    - deploy


before_script:
    - which python
    - which pip
    - /usr/bin/python3 -m pip install --upgrade pip
    - /usr/bin/python3 -m pip install --upgrade mkdocs
    - /usr/bin/python3 -m pip install --upgrade mkdocs-material
    - /usr/bin/python3 -m pip install --upgrade pymdown-extensions
build:
    stage: deploy
    environment:
        name: Testing
        url: https://developers.gambio.de/docs/manual/
    script:
        - '# generate manual with mkdocs'
        - export
        - ./src/build.sh ${CI_COMMIT_TAG}
        - rm -r .git # Remove git directory before upload
        - ssh redmine "mkdir /var/www/developers.gambio.de/docs/manual/${CI_COMMIT_TAG}/"
        - scp -r ./dist/${CI_COMMIT_TAG}/* redmine:/var/www/developers.gambio.de/docs/manual/${CI_COMMIT_TAG}/
    only:
        - tags