##
## DEPLOYMENT
##

# Updated new manuel to developers.gambio.de page

stages:
    - deploy


before_script:
    - which python
    - which pip
    - /usr/bin/python3 -m pip install --upgrade pip
    - /usr/bin/python3 -m pip install --upgrade mkdocs
    - /usr/bin/python3 -m pip install --upgrade mkdocs-material
    - /usr/bin/python3 -m pip install --upgrade pymdown-extensions
build:
    stage: deploy
    environment:
        name: Testing
        url: https://developers.gambio.de/docs/manual/
    script:
        - '# generate manual with mkdocs'
        - export
        - ./src/build.sh v4.3.2.1
        - rm -r .git # Remove git directory before upload
        - ssh redmine 'rm -r /var/www/developers.gambio.de/docs/manual/; mkdir /var/www/developers.gambio.de/docs/manual/'
        - scp -r ./dist/* redmine:/var/www/developers.gambio.de/docs/manual/
    only:
        - master