##
## DEPLOYMENT
##

# Updated new manuel to developers.gambio.de page

stages:
    - build
    - deploy


before_script:
    - python -m pip install --upgrade pip && python -m pip install mkdocs
build:
    stage: build
    script:
        - '# generate manual with mkdocs'
        - ./src/build.sh v4.2.0.0
    only:
        - master


upload:
    stage: deploy
    environment:
        name: Testing
        url: https://tt.supp.gambio-server.net/manual/
    script:
        - '# Removed files that should not be deployed'
        - rsync -a --delete dist/ testshops:/var/www/tt/manual/
    only:
        - master
