site_name: Handbuch Gambio Shopsystem
site_url: https://developers.gambio.de/
docs_dir: ./docs
site_dir: ./../dist/a-version
copyright: Copyright &copy; 2021 Gambio GmbH
theme:
  name: null
  highlightjs: true
  custom_dir: ../node_modules/mkdocs-material/material
  favicon: _assets/favicon.ico
  language: de
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: _assets/logo.svg
  feature:
    tabs: true
  sticky_navigation: true
  collapse_navigation: false
  features:
    - search.highlight
    - toc.autohide
    - navigation.tabs
    - navigation.sections
extra:
  social:
    - type: gitlab
      link: https://sources.gambio-server.net
    - type: twitter
      link: https://twitter.com/gambio
    - type: linkedin
      link: https://www.linkedin.com/company/gambio-gmbh
extra_css:
  - _assets/extra.css
  - _assets/highlight-js-docco.min.css
extra_javascript:
  - _assets/highlight-js.min.js
  - _assets/extra.js
markdown_extensions:
  - extra
  - admonition
  - meta
  - attr_list
  - toc:
      baselevel: 2
      toc_depth: 3
plugins:
  - search:
      lang: de
      separator: '[\s]+'