site_name: Handbuch
site_url: https://developers.gambio.de/docs/manual
docs_dir: ./docs
site_dir: ./../dist/a-version
copyright: Copyright &copy; 2023 Gambio GmbH
theme:
  name: material
  custom_dir: html
  favicon: favicon.ico
  logo: logo.svg
  language: de
  palette:
    scheme: gambio
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - toc.autohide
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - navigation.top
extra:
  generator: false
  social:
    - icon: gambio/white
      link: https://www.gambio-support.de
      name: Gambio Kundenportal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gambio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gambio-gmbh
extra_css:
  - assets/css/extra.css
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - html/.icons
  - def_list
  - footnotes
  - abbr
  - extra
  - admonition
  - meta
  - attr_list
  - markdown_image_caption.plugin
  - toc:
      toc_depth: 6
      permalink: true
plugins:
  - section-index
  - mkdocs-nav-enhancements
  - search:
      lang: de
      separator: '[\s\-\.]+'
