site_name: Handbuch
site_url: https://developers.gambio.de/docs/manual
docs_dir: ./docs
site_dir: ./../dist/a-version
copyright: Copyright &copy; 2024 Gambio GmbH
theme:
  name: material
  custom_dir: html
  favicon: favicon.ico
  logo: logo.svg
  language: de
  palette:
    theme:
      palette:
        -   media: "(prefers-color-scheme)"
            toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        -   media: "(prefers-color-scheme: light)"
            scheme: gambio
            toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            toggle:
              icon: material/brightness-4
              name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - toc.autohide
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - navigation.top
extra:
  generator: false
  social:
    - icon: gambio/white
      link: https://www.gambio-support.de
      name: Gambio Kundenportal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gambio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gambio-gmbh
extra_css:
  - assets/css/extra.css
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - html/.icons
  - def_list
  - footnotes
  - abbr
  - extra
  - admonition
  - meta
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 6
      permalink: true
plugins:
  - section-index
  - mkdocs-nav-enhancements
  - tags
  - search:
      lang: de
      separator: '[\s\-\.]+'
