site_name: Handbuch Gambio Shopsystem
site_url: https://developers.gambio.de/
docs_dir: ./docs
site_dir: ./../dist/a-version
copyright: Copyright &copy; 2021 Gambio GmbH
theme:
  name: material
  favicon: _assets/favicon.ico
  logo: _assets/logo.svg
  language: de
  palette:
    scheme: gambio
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide
    - toc.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://sources.gambio-server.net
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gambio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gambio-gmbh
extra_css:
  - _assets/extra.css
  - _assets/highlight-js-docco.min.css
extra_javascript:
  - _assets/highlight-js.min.js
  - _assets/extra.js
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - def_list
  - footnotes
  - abbr
  - extra
  - admonition
  - meta
  - attr_list
  - toc:
      baselevel: 2
      toc_depth: 4
      permalink: true
plugins:
  - search:
      lang: de
      separator: '[\s\-\.]+'