            - name: MkDocs Action
  # You may pin to the exact commit or the version.
  # uses: Tiryoh/actions-mkdocs@c9944d37d46488196a79d8d5e128c1d2af8f3d78
  uses: Tiryoh/actions-mkdocs@v0.23.0
  with:
    # pip version of MkDocs
    mkdocs_version: # optional, default is latest
    # path to requirements.txt
    requirements: # optional, default is requirements.txt
    # path to mkdocs.yml
    configfile: src/mkdocs.yml
